# Generated by Django 4.0.3 on 2022-03-26 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='horarios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agendamento.horario'),
        ),
    ]
