# Generated by Django 4.0.3 on 2022-03-26 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('crm', models.CharField(max_length=30)),
                ('especialidades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.especialidade')),
            ],
        ),
    ]
