# Generated by Django 4.0.3 on 2022-03-26 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_medico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='especialidades',
            new_name='especialidade',
        ),
    ]
