# Generated by Django 4.0.3 on 2022-03-26 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_agenda_horarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='horarios',
            new_name='horario',
        ),
    ]
