# Generated by Django 4.0.3 on 2022-03-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0003_rename_horarios_agenda_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='horario',
        ),
        migrations.AddField(
            model_name='agenda',
            name='horario',
            field=models.ManyToManyField(to='agendamento.horario'),
        ),
    ]
