# Generated by Django 4.0.3 on 2022-03-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0003_rename_especialidades_medico_especialidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='telefone',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.CharField(max_length=6),
        ),
    ]
