# Generated by Django 4.0.3 on 2022-03-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0004_medico_email_medico_telefone_alter_medico_crm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='medico',
            name='telefone',
            field=models.CharField(max_length=9),
        ),
    ]
