# Generated by Django 4.0.3 on 2022-03-26 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0004_remove_agenda_horario_agenda_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='medico',
        ),
    ]
