# Generated by Django 4.0.3 on 2022-03-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0005_alter_medico_email_alter_medico_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='telefone',
            field=models.CharField(max_length=30),
        ),
    ]
