# Generated by Django 4.0.3 on 2022-03-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0006_agenda_medico'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='horario',
            field=models.ManyToManyField(to='agendamento.horario'),
        ),
    ]
