# Generated by Django 4.0.3 on 2022-03-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0008_alter_agenda_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
