# Generated by Django 4.0.3 on 2022-03-29 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0009_alter_medico_crm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamento.medico'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicos', to='agendamento.especialidade'),
        ),
    ]
