# Generated by Django 4.0.3 on 2022-03-29 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0010_alter_agenda_medico_alter_medico_especialidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='horario',
        ),
        migrations.AddField(
            model_name='horario',
            name='agenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='agendamento.agenda'),
        ),
    ]
