# Generated by Django 4.0.3 on 2022-03-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0011_remove_agenda_horario_horario_agenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='agenda',
        ),
        migrations.AddField(
            model_name='agenda',
            name='horario',
            field=models.ManyToManyField(blank=True, to='agendamento.horario'),
        ),
    ]
