# Generated by Django 4.0.3 on 2022-03-31 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0013_alter_medico_email_alter_medico_especialidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='especialidade',
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidade',
            field=models.ManyToManyField(to='agendamento.especialidade'),
        ),
    ]
