# Generated by Django 4.0.3 on 2022-04-02 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0014_remove_medico_especialidade_medico_especialidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='especialidade',
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agendamento.especialidade'),
        ),
    ]
