# Generated by Django 4.0.3 on 2022-04-03 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0015_remove_medico_especialidade_medico_especialidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='especialidade',
            new_name='especialidade_id',
        ),
    ]
