# Generated by Django 4.0.3 on 2022-04-03 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0016_rename_especialidade_medico_especialidade_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='especialidade_id',
            new_name='especialidade',
        ),
    ]
