# Generated by Django 4.0.3 on 2022-04-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0018_rename_especialidade_medico_especialidade_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidade',
            name='nome',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
